# Site settings
title: Jonathan Day-Reiner
email: contact@18pct.com
url: http://18pct.com
description: "Jonathan Day-Reiner is a DevOps manager, large-format photographer and dad from Toronto, Canada with sixteen years of experience in UNIX systems engineering and architecture."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 18pct.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://careers.stackoverflow.com/dayreiner
  - title: linkedin
    url: https://www.linkedin.com/in/dayreiner
  - title: github
    url: https://github.com/dayreiner
  - title: twitter
    url: https://twitter.com/dayreiner
  - title: facebook
    url: https://facebook.com/dayreiner
  - title: flickr
    url: https://www.flickr.com/photos/groundglass

# Build settings
markdown: kramdown
#permalink: pretty
# Site settings
baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Jonathan Day-Reiner
user_description: "Jonathan Day-Reiner is a DevOps manager, large-format photographer and dad from Toronto, Canada."
user_title: Eighteen Percent Grey
twitter_username: dayreiner
github_username:  dayreiner
gplus_username:  18pct
disqus_username: 18pct

# Build settings
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Blog Home
    url: /blog
  - title: About Me
    url: /about
#  - title: Series
#    url: /series
#  - title: Tags
#    url: /tags
  - title: Homepage
    url: /

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
