# Site settings
title: Jonathan Day-Reiner
email: contact@18pct.com
url: https://dayreiner.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 18pct.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://careers.stackoverflow.com/dayreiner
  - title: linkedin
    url: https://www.linkedin.com/in/dayreiner
  - title: github
    url: https://github.com/dayreiner
  - title: twitter
    url: https://twitter.com/dayreiner
  - title: facebook
    url: https://facebook.com/dayreiner
  - title: flickr
    url: https://www.flickr.com/photos/groundglass

# Build settings
markdown: kramdown
permalink: pretty
